# Generated by Django 4.2.7 on 2023-12-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=50)),
                ('openingtime', models.TextField()),
                ('closingtime', models.TextField()),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('order', models.CharField(max_length=50)),
                ('rating', models.TextField()),
            ],
        ),
    ]
